[package]
name = "custard_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
dialoguer = "0.10.2"
exitcode = "1.1.2"
eyre = "0.6.8"
once_cell = "1.15.0"
rust-i18n = "0.6.1"
